### ISSUE TITLE
Can you make a new release?

### ISSUE THREAD

**Issue by erluti** [raszi/cleanup_vendor#85]
This commit fixes a problem I'm having using this gem in ruby 3: https://github.com/raszi/cleanup_vendor/commit/14da6339d8d9fb306d48e57b2df5fe3aae299c94

Any chance a new release is coming out soon?
Thanks in advance

**Comment by raszi** [comment]
Sure thing. Released as [`v0.6.1`](/raszi/cleanup_vendor/releases/tag/v0.6.1).
